<div align="center">

## **LAPORAN PRAKTIKUM**

## **ALGORITMA DAN PEMROGRAMAN**

## **“Tipe data dan variabel”**

## **Disusun Oleh :**

## **Rahadatul Aisha Tetriana Putri**

## **2611531017**

## **Dosen Pengampu:**

## **Wahyudi.DR.. S.T.M.T**

## **Asisten Praktikum:**

## **Rifki Yuliandra**




<br>

 <img src="images/logo_unand.png" width="200">

<br>

## **FAKULTAS TEKNOLOGI INFORMASI**

## **DEPARTEMEN INFORMATIKA**

## **UNIVERSITAS ANDALAS**

## **2026**

</div>


<h1 align=center> KATA PENGANTAR </h1>

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum Alpro 2 yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan implementasi tipe data numerik, boolean, dan string beserta konstanta dan input pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep bahasa pemrograman Python pada real project.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

<h1 align=center> BAB I <br> PENDAHULUAN </h1>

## 1.1 Latar Belakang
Python merupakan salah satu bahasa pemrograman yang banyak digunakan karena memiliki penulisan yang sederhana dan mudah dipahami. Dalam membuat suatu program, pemahaman terhadap data dan cara pengolahannya diperlukan agar program dapat berjalan sesuai dengan tujuan yang diinginkan. Pada praktikum ini, dipelajari beberapa konsep dasar Python, yaitu string, numerik, input, boolean, dan konstanta. String digunakan untuk mengolah data berupa teks, numerik digunakan dalam pengolahan angka, input digunakan untuk menerima data dari pengguna, boolean digunakan dalam menentukan suatu kondisi, sedangkan konstanta digunakan untuk menyimpan nilai yang tetap. Melalui praktikum ini, kelima konsep tersebut diterapkan dalam beberapa program sederhana sehingga dapat membantu memahami penggunaan dasar Python dalam pembuatan program.

## 1.2 Tujuan
1. Memahami konsep dan penggunaan tipe data string dan numerik dalam bahasa pemrograman Python.
2. Memahami penggunaan input dan boolean untuk menerima data serta menentukan kondisi dalam suatu program.
3. Mengetahui cara menggunakan konstanta dalam proses pembuatan program sederhana menggunakan Python.

## 1.3 Manfaat
1. Menambah pemahaman mengenai penggunaan berbagai tipe data dan  variabel dalam bahasa pemrograman Python.
2. Membantu menerapkan string, numerik, input, boolean, dan konstanta dalam pembuatan program sederhana.

<h1 align=center> BAB II <br> PEMBAHASAN </h1>

## 2.1 Dasar Teori
Pada praktikum ini dibahas beberapa materi dasar dalam bahasa pemrograman Python, yaitu string, numerik, input, boolean, dan konstanta. Materi tersebut digunakan dalam membuat program sederhana dan memiliki fungsi yang berbeda sesuai dengan kebutuhan program. Dasar teori dari masing-masing materi yang dipelajari adalah sebagai berikut:

### 2.1.1 String <br>
String merupakan tipe data yang digunakan untuk menyimpan data berupa teks atau kumpulan karakter. String dapat berisi huruf, angka, simbol, maupun kalimat. Dalam Python, string biasanya ditulis menggunakan tanda petik satu (' ') atau tanda petik dua (" "). Tipe data ini sering digunakan untuk menyimpan informasi yang berupa teks, seperti nama, alamat, jenis kelamin, dan agama.

### 2.1.2 Numerik <br>
 Numerik merupakan tipe data yang digunakan untuk menyimpan nilai berupa angka. Python memiliki beberapa jenis data numerik, di antaranya int untuk bilangan bulat, float untuk bilangan desimal, dan complex untuk bilangan kompleks. Tipe data numerik dapat digunakan dalam berbagai operasi matematika seperti penjumlahan, pengurangan, perkalian, dan pembagian.

### 2.1.3 Input <br> 
Input merupakan proses memasukkan data ke dalam program dari pengguna. Pada Python, fungsi input() digunakan untuk meminta masukan dari pengguna ketika program sedang dijalankan. Dengan adanya input, program dapat menerima nilai yang berbeda sesuai dengan data yang dimasukkan oleh pengguna. Data yang diterima melalui input() pada dasarnya berupa string. Jika data tersebut akan digunakan sebagai angka dalam perhitungan, data perlu diubah terlebih dahulu menggunakan fungsi seperti int() atau float(). Dengan demikian, input dapat digunakan untuk membuat program yang lebih interaktif.

### 2.1.4 Boolean <br> 
Boolean merupakan tipe data yang digunakan untuk menyatakan nilai kebenaran suatu kondisi. Boolean hanya memiliki dua nilai, yaitu True dan False. Nilai tersebut dapat diperoleh dari hasil perbandingan maupun digunakan secara langsung dalam program. Boolean sering digunakan ketika program perlu menentukan apakah suatu kondisi benar atau salah.

### 2.1.5 Konstanta <br> 
Konstanta adalah nilai yang digunakan sebagai nilai tetap dalam program. Dalam Python terdapat beberapa konstanta bawaan, seperti True, False, dan None. Nilai True dan False berkaitan dengan tipe data boolean, sedangkan None digunakan untuk menunjukkan tidak adanya suatu nilai. Konstanta bawaan tersebut memiliki aturan khusus dan tidak dapat diberi nilai baru.


## 2.2 Kode Program

### 2.2.1 Program "String_2611531017"


In [ ]:
nama_1017 = "raha"
jenis_kelamin_1017= "P"
alamat_1017 = """
    Kampus Unand
    kec.pauh
    kota Padang
"""
agama_1017 = "islam"
print ("Nama saya adalah:", nama_1017)
print ("Jenis kelamin saya adalah:", jenis_kelamin_1017)
print ("Alamat saya adalah:", alamat_1017)
print ("Agama saya adalah:", agama_1017)

Nama saya adalah: raha
Jenis kelamin saya adalah: P
Alamat saya adalah: 
    Kampus Unand
    kec.pauh
    kota Padang

Agama saya adalah: islam


**Penjelasan:**
1. Baris 1 berfungsi untuk menyimpan data nama "raha" ke dalam variabel nama_1017 sebagai tipe data string. Variabel tersebut digunakan untuk menyimpan nama yang akan ditampilkan pada output program.
2. Baris 2 berfungsi untuk menyimpan data jenis kelamin "P" ke dalam variabel jenis_kelamin_1017 sebagai tipe data string. Nilai tersebut nantinya digunakan untuk menampilkan informasi jenis kelamin.
3. Baris 3–7 berfungsi untuk menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris, dengan """ sebagai tanda pembuka dan penutup string. Penggunaan tanda tersebut memungkinkan alamat ditulis dalam lebih dari satu baris.
4. Baris 8 berfungsi untuk menyimpan data agama "islam" ke dalam variabel agama_1017 sebagai tipe data string. Data tersebut digunakan sebagai informasi agama yang akan ditampilkan.
5. Baris 9–12 berfungsi untuk menampilkan data nama, jenis kelamin, alamat, dan agama menggunakan print() sebagai syntax untuk mencetak output program. Tanda koma , digunakan untuk memisahkan teks dengan variabel yang ingin ditampilkan.

### 2.2.2 Program "Numerik_2611531017"

In [ ]:
#create a variable with integer value
a_1017=100
print("The type of variable having value",a_1017,"is",type(a_1017))
#create a variable with float value
b_1017=10.2345
print("The type of variable having value",b_1017,"is",type(b_1017))
#create a variable with complex value
c_1017=100+3j
print("The type of variable having value",c_1017,"is",type(c_1017))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan**
1. Baris 1 berfungsi sebagai komentar yang menjelaskan bahwa program akan membuat variabel dengan nilai numerik.
2. Baris 2 berfungsi untuk menyimpan nilai 100 ke dalam variabel a_1017. Nilai tersebut termasuk tipe data integer (int) karena merupakan bilangan bulat.
3. Baris 3 berfungsi untuk menampilkan nilai variabel a_1017 beserta tipe datanya menggunakan print() dan type().
4. Baris 4 berfungsi sebagai komentar yang menjelaskan pembuatan variabel dengan nilai desimal.
5. Baris 5 berfungsi untuk menyimpan nilai 10.2345 ke dalam variabel b_1017. Nilai tersebut termasuk tipe data float karena memiliki angka di belakang koma.
6. Baris 6 berfungsi untuk menampilkan nilai variabel b_1017 beserta tipe datanya menggunakan print() dan type().
7. Baris 7 berfungsi sebagai komentar yang menjelaskan pembuatan variabel dengan nilai bilangan kompleks.
8. Baris 8 berfungsi untuk menyimpan nilai 100+3j ke dalam variabel c_1017. Nilai tersebut termasuk tipe data complex karena memiliki bagian bilangan real dan imajiner yang ditandai dengan j.
9. Baris 9 berfungsi untuk menampilkan nilai variabel c_1017 beserta tipe datanya menggunakan print() dan type().


### 2.2.3 Program "Input_2611531017"

In [13]:
# Buat file dengan nama Input_1017.py
# Buat progam untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_1017
# Progam ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_1017 = input('Masukkan nilai panjang: ')
lebar_1017 = input('Masukkan nilai lebar: ')
luas_1017 = int(panjang_1017) * int(lebar_1017)
print("Luas =", luas_1017)

Luas = 300


**Penjelasan**
1. Baris 1–6 berfungsi sebagai komentar yang memberikan keterangan mengenai nama file, tujuan program, aturan penamaan variabel, serta konsep input() yang digunakan dalam program. Komentar tersebut tidak dijalankan sebagai bagian dari proses program.
2. Baris 7 berfungsi untuk meminta pengguna memasukkan nilai panjang persegi panjang menggunakan fungsi input(). Nilai yang dimasukkan kemudian disimpan ke dalam variabel panjang_1017.
3. Baris 8 berfungsi untuk meminta pengguna memasukkan nilai lebar persegi panjang menggunakan fungsi input(). Nilai tersebut disimpan ke dalam variabel lebar_1017.
4. Baris 9 berfungsi untuk menghitung luas persegi panjang dengan mengalikan nilai panjang dan lebar. Fungsi int() digunakan untuk mengubah nilai yang diperoleh dari input() dari tipe data string menjadi integer agar dapat digunakan dalam operasi perkalian. Hasil perhitungan kemudian disimpan dalam variabel luas_1017.
5. Baris 10 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang menggunakan fungsi print(). Teks "Luas =" digunakan sebagai keterangan, sedangkan luas_1017 menampilkan nilai hasil perhitungannya.

### 2.2.4 Program "Boolean_2611531017"

In [11]:
# deklarasi variabel dengan tipe data Boolean
is_lulus_1017 = True
is_cumlaude_1017 = True

# Menggunakan Boolean
nilai_1017 = 85
batas_lulus_1017 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_1017= nilai_1017 >= batas_lulus_1017 # Hasilnya akan True

print("=== Check Kelulusan===")
print("Nilai:", nilai_1017)
print("Apakah Lulus?", status_kelulusan_1017)
if is_lulus_1017 and is_cumlaude_1017:
    print("Selamat, Anda lulus dengan predikat Cum Laude! ")

=== Check Kelulusan===
Nilai: 85
Apakah Lulus? True
Selamat, Anda lulus dengan predikat Cum Laude! 


**Penjelasan**
1. Baris 1 berfungsi sebagai komentar yang memberikan keterangan bahwa kode di bawahnya merupakan deklarasi variabel dengan tipe data Boolean. Komentar tersebut tidak dijalankan sebagai bagian dari proses program.
2. Baris 2 berfungsi untuk mendeklarasikan variabel is_lulus_1017 dan memberinya nilai Boolean True, yang menandakan status kelulusan bernilai benar.
3. Baris 3 berfungsi untuk mendeklarasikan variabel is_cumlaude_1017 dan memberinya nilai Boolean True, yang menandakan status cum laude bernilai benar.
4. Baris 5 berfungsi sebagai komentar yang menjelaskan bahwa bagian program selanjutnya menunjukkan penggunaan tipe data Boolean dalam sebuah kondisi.
5. Baris 6 berfungsi untuk mendeklarasikan variabel nilai_1017 dan memberinya nilai integer 85, yang merepresentasikan nilai akhir mahasiswa.
6. Baris 7 berfungsi untuk mendeklarasikan variabel batas_lulus_1017 dan memberinya nilai integer 75, yang merepresentasikan batas minimal nilai kelulusan.
7. Baris 9 berfungsi sebagai komentar yang menjelaskan bahwa baris berikutnya digunakan untuk menentukan nilai Boolean berdasarkan hasil suatu kondisi.
8. Baris 10 berfungsi untuk menentukan status kelulusan dengan membandingkan nilai_1017 dan batas_lulus_1017 menggunakan operator relasional >= (lebih besar sama dengan). Karena 85 >= 75 bernilai benar, hasil perbandingan berupa Boolean True disimpan dalam variabel status_kelulusan_1017.
9. Baris 12 berfungsi untuk menampilkan teks "=== Check Kelulusan===" sebagai judul atau header keluaran program menggunakan fungsi print().
10. Baris 13 berfungsi untuk menampilkan teks "Nilai:" beserta nilai variabel nilai_1017 menggunakan fungsi print(), sehingga pengguna dapat melihat nilai yang diperoleh.
11. Baris 14 berfungsi untuk menampilkan teks "Apakah Lulus?" beserta nilai variabel status_kelulusan_1017 menggunakan fungsi print(), sehingga hasil Boolean dari kondisi kelulusan dapat ditampilkan.
12. Baris 15 berfungsi untuk membuat percabangan kondisi menggunakan pernyataan if dengan operator logika and, yang akan bernilai True hanya jika kedua variabel is_lulus_1017 dan is_cumlaude_1017 bernilai True.
13. Baris 16 berfungsi untuk menampilkan teks "Selamat, Anda lulus dengan predikat Cum Laude!" menggunakan fungsi print(), yang hanya akan dieksekusi apabila kondisi pada baris 15 terpenuhi.


### 2.2.5 Program "Konstanta_2611531017"

In [12]:
# Buat file dengan nama Konstanta_1017.py
# Progam ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1017

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_1017 = float(input('Masukan nilai jari-jari:'))
luas_1017 = PI * jari_1017 * jari_1017
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1017, luas_1017))

pi: 3.140000
Luas lingkaran dengan jari-jari 66.00 adalah 13677.84


**Penjelasan**
1. Baris 1 sampai 3 adalah komentar yang berisi keterangan tentang nama file, tujuan program, dan aturan penulisan nama variabel. Baris ini hanya catatan dan tidak diproses oleh program.
2. Baris 5 berfungsi mengambil fungsi Final dari modul typing. Fungsi ini digunakan untuk menandai bahwa suatu variabel adalah konstanta, yaitu nilai yang tidak boleh diubah selama program berjalan.
3. Baris 6 berfungsi membuat variabel bernama PI dengan tipe Final dan nilai tetap 3.14. Nilai ini digunakan sebagai nilai pi dalam perhitungan lingkaran.
4. Baris 7 berfungsi menampilkan nilai PI ke layar dengan perintah print(). Tanda %f berarti nilai akan ditampilkan dalam bentuk bilangan pecahan (desimal).
5. Baris 8 berfungsi meminta pengguna memasukkan angka jari-jari lingkaran lewat perintah input(). Perintah float() digunakan agar angka yang dimasukkan pengguna, yang awalnya berbentuk teks, diubah menjadi bilangan desimal. Hasilnya disimpan dalam variabel jari_1017.
6. Baris 9 berfungsi menghitung luas lingkaran dengan rumus pi dikali jari-jari dikali jari-jari (PI × jari_1017 × jari_1017). Hasil hitungannya disimpan dalam variabel luas_1017.
7. Baris 10 berfungsi menampilkan hasil akhir ke layar, yaitu nilai jari-jari dan luas lingkaran yang sudah dihitung. Tanda %.2f berarti angka yang ditampilkan dibulatkan menjadi dua angka di belakang koma.

<h1 align=center> BAB III <br> KESIMPULAN </h1>

Berdasarkan praktikum yang telah dilaksanakan, dapat disimpulkan bahwa pemahaman mengenai variabel dan tipe data menjadi salah satu dasar yang diperlukan dalam membuat program menggunakan Python. Variabel berfungsi untuk menyimpan suatu nilai atau data, sedangkan tipe data digunakan untuk menunjukkan jenis data yang digunakan dalam program. Pada praktikum ini, tipe data yang dipelajari meliputi numerik, string, dan boolean, serta penggunaan input untuk memasukkan data dari pengguna.

Selain itu, praktikum juga membahas aturan dalam memberikan nama pada variabel dan penggunaan "Final" sebagai konstanta. Melalui praktikum ini, penulis dapat memahami cara menyimpan, menerima, dan mengolah berbagai jenis data dalam Python. Pemahaman tersebut kemudian diterapkan melalui beberapa program sederhana, seperti membuat biodata, menentukan kelulusan, dan menghitung luas persegi panjang.

<h1 align=center> DAFTAR PUSTAKA </h1>

1. Python Software Foundation. (2026). An Informal Introduction to Python — Python 3.14.7 Documentation. https://docs.python.org/3.14/tutorial/introduction.html

2. Python Software Foundation. (2026). Built-in Types — Python 3.14.7 Documentation. https://docs.python.org/3/library/stdtypes.html 

3. Downey, A. (2015). Think Python: How to Think Like a Computer Scientist (2nd ed.). O'Reilly Media. Diakses dari https://greenteapress.com/wp/think-python-2e/

5. Lutz, M. (2013). Learning Python (5th ed.). O'Reilly Media. Diakses dari https://www.oreilly.com/library/view/learning-python-5th/9781449355722/

6. W3Schools. (n.d.). Python Variables and Data Types. Diakses pada 9 September 2026, dari https://www.w3schools.com/python/python_variables.asp

7. GeeksforGeeks. (n.d.). Python Data Types. Diakses pada 9 September 2026, dari https://www.geeksforgeeks.org/python-data-types/